version: "3.7"
services:

  mongo:
    image: mongo:4.2
    logging:
      driver: none
    environment: 
      MONGO_INITDB_DATABASE: dogs
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  integration:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://user:password@mongo:27017
      DATABASE: dogs
      COLLECTION: breedsOfDog
      WAIT_HOSTS: mongo:27017
    depends_on: 
      - mongo
