version: "3.7"
services:

  mongo:
    image: mongo
    logging:
      driver: none
    environment: 
      MONGO_INITDB_DATABASE: dogs
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  pubsub:
    build: 
      context: ./
      dockerfile: pubsub-Dockerfile
    logging:
      driver: none

  integration:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://user:password@mongo:27017
      DATABASE: dogs
      COLLECTION: breedsOfDog
      DOGS_TOPIC: dogs
      SUBSCRIPTION: animals
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_PROJECT_ID: integration-tests
      WAIT_HOSTS: mongo:27017, pubsub:8085
    depends_on: 
      - mongo
      - pubsub
